import { Card } from './types';

export const cards: Card[] = [
  // Food
  { partial: "pancake", full: "pancake house" },
  { partial: "cheese", full: "cheesecake factory" },
  { partial: "hot", full: "hot dog" },
  { partial: "butter", full: "butterfingers" },
  { partial: "egg", full: "egg nog" },
  { partial: "fish", full: "fish stick" },
  { partial: "corn", full: "corn on the cob" },
  { partial: "meatball", full: "spaghetti and meatballs" },
  { partial: "toast", full: "french toast" },
  { partial: "banana", full: "banana split" },
  { partial: "pepper", full: "pepper spray" },
  { partial: "cookie", full: "cookie monster" },
  { partial: "pizza", full: "pizza rat" },
  { partial: "grape", full: "grapefruit" },
  { partial: "taco", full: "taco bell" },
  { partial: "noodle", full: "noodle soup" },
  { partial: "waffle", full: "waffle house" },
  { partial: "pickle", full: "pickle rick" },
  { partial: "bacon", full: "kevin bacon" },

  // Animals
  { partial: "cat", full: "cat burglar" },
  { partial: "dog", full: "dog days of summer" },
  { partial: "bear", full: "bear grylls" },
  { partial: "monkey", full: "monkey business" },
  { partial: "chicken", full: "chicken pox" },
  { partial: "horse", full: "horseback riding" },
  { partial: "shark", full: "shark tank" },
  { partial: "wolf", full: "wolf of wall street" },
  { partial: "bat", full: "batman" },
  { partial: "spider", full: "spider-man" },
  { partial: "bull", full: "bull in a china shop" },
  { partial: "ant", full: "ant farm" },
  { partial: "frog", full: "frogger" },
  { partial: "goat", full: "greatest of all time" },
  { partial: "duck", full: "duck tape" },
  { partial: "fly", full: "fly fishing" },
  { partial: "whale", full: "whale watching" },

  // Sports
  { partial: "slam", full: "slam dunk" },
  { partial: "ball", full: "wrecking ball" },
  { partial: "goal", full: "goalie" },
  { partial: "basket", full: "basketball" },
  { partial: "punch", full: "sucker punch" },
  { partial: "kick", full: "kickboxing" },
  { partial: "strike", full: "bowling strike" },
  { partial: "race", full: "rat race" },
  { partial: "catch", full: "catch-22" },
  { partial: "swim", full: "swimming with sharks" },
  { partial: "wrestle", full: "arm wrestling" },
  { partial: "pitch", full: "pitch perfect" },

  // Pop Culture
  { partial: "star", full: "star wars" },
  { partial: "iron", full: "iron man" },
  { partial: "frozen", full: "frozen yogurt" },
  { partial: "game", full: "game of thrones" },
  { partial: "break", full: "breaking bad" },
  { partial: "stranger", full: "stranger things" },
  { partial: "walking", full: "walking dead" },
  { partial: "black", full: "black panther" },
  { partial: "baby", full: "baby yoda" },
  { partial: "harry", full: "harry potter" },
  { partial: "king", full: "king kong" },
  { partial: "fast", full: "fast and furious" },
  { partial: "hunger", full: "hunger games" },
  { partial: "jurassic", full: "jurassic park" },
  { partial: "finding", full: "finding nemo" },

  // Nature
  { partial: "thunder", full: "thundercat" },
  { partial: "lightning", full: "lightning bug" },
  { partial: "fire", full: "fire truck" },
  { partial: "water", full: "waterfall" },
  { partial: "snow", full: "snowball fight" },
  { partial: "rain", full: "rainbow" },
  { partial: "sun", full: "sunflower" },
  { partial: "moon", full: "moonwalk" },
  { partial: "rock", full: "rock and roll" },
  { partial: "mountain", full: "mountain dew" },
  { partial: "volcano", full: "volcano taco" },
  { partial: "tornado", full: "sharknado" },
  { partial: "sand", full: "sandcastle" },
  { partial: "cloud", full: "cloud nine" },
  { partial: "ice", full: "ice cream sandwich" },
  { partial: "tree", full: "treehouse" },

  // Tech
  { partial: "mouse", full: "computer mouse" },
  { partial: "apple", full: "apple pie" },
  { partial: "web", full: "spider web" },
  { partial: "stream", full: "streaming service" },
  { partial: "crash", full: "crash landing" },
  { partial: "tablet", full: "stone tablet" },
  { partial: "code", full: "cheat code" },
  { partial: "robot", full: "mr. robot" },
  { partial: "space", full: "space jam" },
  { partial: "wire", full: "barbed wire" },
  { partial: "chip", full: "chocolate chip" },
  { partial: "bug", full: "bug zapper" },

  // Mythology
  { partial: "dragon", full: "dragon ball z" },
  { partial: "giant", full: "jolly green giant" },
  { partial: "ghost", full: "ghostbusters" },
  { partial: "troll", full: "troll bridge" },
  { partial: "witch", full: "witch doctor" },
  { partial: "wizard", full: "wizard of oz" },
  { partial: "zombie", full: "zombie apocalypse" },
  { partial: "vampire", full: "vampire weekend" },
  { partial: "unicorn", full: "unicorn frappuccino" },
  { partial: "mermaid", full: "little mermaid" },
  { partial: "phoenix", full: "phoenix rising" },
  { partial: "goblin", full: "green goblin" },

  // Household
  { partial: "chair", full: "chairman" },
  { partial: "bed", full: "bedrock" },
  { partial: "door", full: "doorbell" },
  { partial: "pillow", full: "pillow fight" },
  { partial: "lamp", full: "lava lamp" },
  { partial: "couch", full: "couch potato" },
  { partial: "shower", full: "baby shower" },
  { partial: "clock", full: "clockwork orange" },
  { partial: "mirror", full: "mirror mirror on the wall" },
  { partial: "broom", full: "broomstick" },
  { partial: "pot", full: "pot of gold" },
  { partial: "blanket", full: "security blanket" },

  // Professions
  { partial: "doctor", full: "doctor strange" },
  { partial: "pilot", full: "autopilot" },
  { partial: "spy", full: "spy kids" },
  { partial: "cook", full: "captain cook" },
  { partial: "judge", full: "judge judy" },
  { partial: "pirate", full: "pirates of the caribbean" },
  { partial: "clown", full: "clown car" },
  { partial: "cowboy", full: "space cowboy" },
  { partial: "ninja", full: "ninja turtle" },
  { partial: "knight", full: "dark knight" },
  { partial: "guard", full: "lifeguard" },
  { partial: "chief", full: "master chief" },

  // Geography
  { partial: "island", full: "treasure island" },
  { partial: "jungle", full: "jungle book" },
  { partial: "bridge", full: "bridge over troubled water" },
  { partial: "desert", full: "desert storm" },
  { partial: "cave", full: "bat cave" },
  { partial: "swamp", full: "swamp thing" },
  { partial: "river", full: "river dance" },
  { partial: "hill", full: "king of the hill" },
  { partial: "canyon", full: "grand canyon" },
  { partial: "north", full: "north pole" },

  // Music
  { partial: "drum", full: "drum roll" },
  { partial: "guitar", full: "air guitar" },
  { partial: "horn", full: "unicorn horn" },
  { partial: "bell", full: "bell pepper" },
  { partial: "trumpet", full: "trumpet player" },
  { partial: "piano", full: "piano man" },
  { partial: "string", full: "silly string" },
  { partial: "beat", full: "heartbeat" },
  { partial: "bass", full: "bass drop" },
  { partial: "tune", full: "looney tunes" },

  // Movies & TV
  { partial: "top", full: "top gun" },
  { partial: "mad", full: "mad max" },
  { partial: "fight", full: "fight club" },
  { partial: "scream", full: "ice cream scream" },
  { partial: "ring", full: "lord of the rings" },
  { partial: "man", full: "pac-man" },
  { partial: "speed", full: "speed racer" },
  { partial: "jaws", full: "jaws of life" },
  { partial: "alien", full: "alien vs predator" },
  { partial: "grease", full: "elbow grease" },

  // Absurd Combos
  { partial: "brain", full: "brain freeze" },
  { partial: "elbow", full: "elbow macaroni" },
  { partial: "tongue", full: "tongue twister" },
  { partial: "belly", full: "belly flop" },
  { partial: "tooth", full: "tooth fairy" },
  { partial: "finger", full: "lady fingers" },
  { partial: "head", full: "headband" },
  { partial: "eye", full: "evil eye" },
  { partial: "nose", full: "nose dive" },
  { partial: "foot", full: "bigfoot" },
  { partial: "bone", full: "funny bone" },
  { partial: "thumb", full: "thumbtack" },

  // Everyday Items
  { partial: "key", full: "key lime pie" },
  { partial: "wheel", full: "wheel of fortune" },
  { partial: "shoe", full: "horseshoe" },
  { partial: "flag", full: "capture the flag" },
  { partial: "chain", full: "chain reaction" },
  { partial: "rope", full: "jump rope" },
  { partial: "ladder", full: "ladder to heaven" },
  { partial: "crown", full: "crown jewels" },
  { partial: "hammer", full: "mc hammer" },
  { partial: "nail", full: "nail in the coffin" },
  { partial: "stick", full: "stick figure" },
  { partial: "box", full: "jack in the box" },
  { partial: "cup", full: "world cup" },
  { partial: "candle", full: "candle in the wind" },
  { partial: "glove", full: "boxing glove" },
  { partial: "mask", full: "masquerade" },
  { partial: "sword", full: "swordfish" },
  { partial: "gold", full: "goldilocks" },
  { partial: "trap", full: "booby trap" },
  { partial: "bottle", full: "bottle rocket" },
  { partial: "net", full: "butterfly net" },
  { partial: "stamp", full: "rubber stamp" },
  { partial: "peanut", full: "peanut butter and jelly" },
  { partial: "bubble", full: "bubble bath" },
  { partial: "treasure", full: "treasure hunt" },
];
